apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - mounted-data-pvc.yaml

patches:
  - path: streamlit-mount.yaml
    target:
      kind: Deployment
      name: streamlit
  - path: rq-worker-mount.yaml
    target:
      kind: Deployment
      name: rq-worker
  - path: configmap-local-data-dir.yaml
    target:
      kind: ConfigMap
      name: streamlit-config
