apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
spec:
  template:
    spec:
      containers:
        - name: streamlit
          volumeMounts:
            - name: mounted-data
              mountPath: /mounted-data
              readOnly: true
      volumes:
        - name: mounted-data
          persistentVolumeClaim:
            claimName: mounted-data-pvc
            readOnly: true
