"""
Real-data validation of the OpenMS-Insight migration against the bundled
example workspace (example-data/workspaces/default).

Unlike test_long_format.py (synthetic), these feed the ACTUAL cached parquet
frames through the long-format adapters and OpenMS-Insight components, checking
row counts and filter fidelity end-to-end. They are skipped automatically if the
example data or openms_insight is not present, so they never break a minimal CI.

Findings encoded here:
- deconv_spectrum explodes to exactly sum(len(MonoMass)) peaks; filtering
  index==k reproduces the old iloc[k] scan slice.
- threedim_SN_plot needs OPTIONAL massIndex: scan-only shows all of a scan's
  signal/noisy peaks; massIndex isolates one mass.
- density_decoy is empty with Null-typed columns (empty-decoy path).
"""

import glob
import gzip
import os
import pickle
import sys

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

pl = pytest.importorskip("polars")

DEFAULT_WS = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "example-data",
    "workspaces",
    "default",
)
FD = os.path.join(DEFAULT_WS, "flashdeconv", "cache", "files", "example_fd")

pytestmark = pytest.mark.skipif(
    not os.path.isdir(FD), reason="example workspace data not available"
)

# openms_insight is an optional dependency for these integration checks
oi = pytest.importorskip("openms_insight")

from src.parse.long_format import (  # noqa: E402
    explode_signal_peaks_long,
    explode_spectrum_long,
)


def _mock_session(monkeypatch):
    import streamlit as st

    monkeypatch.setattr(st, "session_state", {}, raising=False)


def test_deconv_spectrum_explodes_to_exact_peak_count():
    src = pl.read_parquet(f"{FD}/deconv_spectrum.pq")
    expected = sum(len(a) for a in src["MonoMass"].to_list())
    out = explode_spectrum_long(src.lazy()).collect()
    assert out.height == expected
    assert out.columns == ["index", "mass", "intensity", "mass_id"]


def test_deconv_lineplot_value_filter_matches_iloc(tmp_path, monkeypatch):
    _mock_session(monkeypatch)
    from openms_insight import LinePlot

    src = pl.read_parquet(f"{FD}/deconv_spectrum.pq")
    long = explode_spectrum_long(src.lazy())
    lc = long.collect()
    lp = LinePlot(
        cache_id="rt_deconv",
        data=long,
        filters={"scanIndex": "index"},
        x_column="mass",
        y_column="intensity",
        cache_path=str(tmp_path),
    )
    idx = int(lc["index"][0])
    vd = lp._prepare_vue_data({"scanIndex": idx})
    assert len(vd["plotData"]) == lc.filter(pl.col("index") == idx).height


def test_3d_optional_massindex_on_real_data(tmp_path, monkeypatch):
    _mock_session(monkeypatch)
    from openms_insight import Scatter3D

    long = explode_signal_peaks_long(
        pl.read_parquet(f"{FD}/threedim_SN_plot.pq").lazy()
    )
    snc = long.collect()
    s3 = Scatter3D(
        cache_id="rt_3d",
        data=long,
        filters={"scanIndex": "index"},
        optional_filters={"massIndex": "mass_id"},
        cache_path=str(tmp_path),
    )
    # pick the scan with the most peaks
    busiest = snc.group_by("index").len().sort("len", descending=True)
    sidx = int(busiest["index"][0])
    scan_only = len(s3._prepare_vue_data({"scanIndex": sidx})["scatter3dData"])
    assert scan_only == snc.filter(pl.col("index") == sidx).height
    # isolate mass 0
    expect_mass0 = snc.filter(
        (pl.col("index") == sidx) & (pl.col("mass_id") == 0)
    ).height
    got = len(
        s3._prepare_vue_data({"scanIndex": sidx, "massIndex": 0})["scatter3dData"]
    )
    assert got == expect_mass0


def test_density_decoy_is_empty_null_typed():
    """The bundled FD run has no decoys: density_decoy is empty, Null-typed."""
    dec = pl.read_parquet(f"{FD}/density_decoy.pq")
    assert dec.height == 0


def test_internal_fragment_map_matches_current_original():
    """Our InternalFragmentMap port matches the CURRENT FLASHApp algorithm.

    (The bundled internal_fragment_data.pkl.gz is stale — generated by an older
    algorithm version while the feature was disabled — so we compare against the
    live src.render.sequence implementation, not the cached file.)
    """
    from openms_insight.components.internalfragmentmap import (
        internal_fragment_masses,
    )
    from src.render.sequence import getInternalFragmentDataFromSeq

    tnt_dirs = glob.glob(
        os.path.join(
            DEFAULT_WS, "flashtnt", "cache", "files", "*antibody*"
        )
    )
    if not tnt_dirs:
        pytest.skip("TnT antibody example not available")
    with gzip.open(os.path.join(tnt_dirs[0], "sequence_data.pkl.gz"), "rb") as f:
        seqdata = pickle.load(f)

    seq = "".join(seqdata[0]["sequence"])
    ref = getInternalFragmentDataFromSeq(seq)
    for ion_type in ("by", "bz", "cy"):
        ours = internal_fragment_masses(seq, ion_type)[0]
        assert len(ours) == len(ref[f"fragment_masses_{ion_type}"])


def test_featureview_explode_real_quant():
    from openms_insight import FeatureView

    q = os.path.join(
        DEFAULT_WS, "flashquant", "cache", "files", "example", "quant_dfs.pq"
    )
    if not os.path.isfile(q):
        pytest.skip("quant example not available")
    qdf = pl.read_parquet(q)
    long = FeatureView.explode_traces(qdf)
    assert long.height > 0
    assert set(long.columns) >= {
        "feature_group",
        "charge",
        "mz",
        "rt",
        "intensity",
    }
    # Every feature group present in the source appears in the long output
    assert set(long["feature_group"].unique().to_list()) <= set(
        qdf["FeatureGroupIndex"].to_list()
    )
