name: Docker Image CI

on:
  push:
    branches: [ "main", "develop", "deploy"]
  pull_request:
    branches: [ "main", "develop", "deploy"]

jobs:

  build-full-app:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test Docker build without exporting layers
        run: docker build --target run-app -f Dockerfile .